<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.AsyncEnumerable" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DbExtensions\Properties\AssemblyInfo.cs" Link="Properties\AssemblyInfo.cs" />
    <Compile Include="..\DbExtensions\Database.cs" Link="Database.cs" />
    <Compile Include="..\DbExtensions\SqlBuilder.cs" Link="SqlBuilder.cs" />
    <Compile Include="..\DbExtensions\SqlSet.cs" Link="SqlSet.cs" />
    <Compile Include="..\DbExtensions\SqlSet.Async.cs" Link="SqlSet.Async.cs" />
  </ItemGroup>

</Project>
