<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <DefineConstants>DBEX_NO_DYN;DBEX_NO_POCO</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\DbExtensions\Database.cs" Link="Database.cs" />
    <Compile Include="..\DbExtensions\SqlBuilder.cs" Link="SqlBuilder.cs" />
    <Compile Include="..\DbExtensions\SqlSet.cs" Link="SqlSet.cs" />
  </ItemGroup>

</Project>
