<Project>

  <PropertyGroup>
    <AssemblyName>DbExtensions</AssemblyName>
    <AssemblyTitle>$(AssemblyName) Query Edition</AssemblyTitle>
    <PackageId>$(AssemblyName)-QE</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <Import Project="..\DbExtensions\DbExtensions.csproj" />

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);DBEX_QE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\DbExtensions\Database.cs" Link="Database.cs" />
    <Compile Include="..\DbExtensions\DynamicMapper.cs" Link="DynamicMapper.cs" />
    <Compile Include="..\DbExtensions\Extensions.cs" Link="Extensions.cs" />
    <Compile Include="..\DbExtensions\Mapper.cs" Link="Mapper.cs" />
    <Compile Include="..\DbExtensions\PocoMapper.cs" Link="PocoMapper.cs" />
    <Compile Include="..\DbExtensions\Properties\AssemblyInfo.cs" Link="Properties\AssemblyInfo.cs" />
    <Compile Include="..\DbExtensions\SqlBuilder.cs" Link="SqlBuilder.cs" />
    <Compile Include="..\DbExtensions\SqlSet.Async.cs" Link="SqlSet.Async.cs" />
    <Compile Include="..\DbExtensions\SqlSet.cs" Link="SqlSet.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
