<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Samples.VisualBasic</RootNamespace>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>16</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DbExtensions\DbExtensions.csproj" />
  </ItemGroup>

</Project>
