<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>7</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Northwind.fs" />
    <Compile Include="SqlBuilder.fs" />
    <Compile Include="SqlSet.fs" />
    <Compile Include="Database.Annotated.fs" />
    <Compile Include="Database.Poco.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DbExtensions\DbExtensions.csproj" />
  </ItemGroup>

</Project>
